# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            LSDTopoTools
tagline:          Open source geomorphology
description:      ""
url:              http://lsdtopotools.github.io/
baseurl:          /

author:
  name:           'Edinburgh LSD'
  url:

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/LSDtopotools
